### PR TITLE
bower and bower-installer moved to devDependencies

### PR DESCRIPTION
**Pull request by nkoder**

### CODE REVIEW

**Comment by nkoder** [comment]
It's about #15

**Comment by julmot** [comment]
Also about #10

**Comment by pwang2** [comment]
Seems last commit is 2015 dec.   I also feel bad about these easy but not fixed stuff.  
Also, this referred  bower-installer is also a fork not merged.
   "bower-installer": "git://github.com/bessdsv/bower-installer.git#temp"

To me, bower-installer should already have been fixed by [shallowCloneHosts](https://github.com/bower/spec/blob/master/config.md#shallowclonehosts) and [wiredep overrides](https://github.com/taptapship/wiredep#bower-overrides)

Another fork for clean up?

**Review by nc93a — APPROVED** [review]
git://github.com/bessdsv/bower-installer.git#temp

**Pull request closed without merging**
